---
- name: update web servers
  hosts: all
  become: yes

  tasks:
  - name: ensure apache is installed
    package:
      name: httpd
      state: present

  - name: ensure apache is started
    service:
      name: httpd
      state: started

  - name: ensure apache is enabled
    service:
      name: httpd
      enabled: yes
...
