---

  - name: ensure apache is started
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: ensure apache is started
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
...
